### ISSUE TITLE
Failure to start pods: Apparmour not installed on Debian Bullseye

### ISSUE THREAD

**Issue by jensens** [k3s-io/k3s-ansible#196]
I use Hetzner Cloud machines with Debian Bullseye. Everything looked fine after the Ansible script executed, but a closer look revealed: Not a single pod came up successfully.

The solution was found by a look into the logs: `apparmour_parser` was not there.

I appended the following lines to `roles/prereq/tasks/main.yml` and the problem was gone.  

```
 - name: Install Apparmour
  package:
    name: apparmor
    state: present
```
