### ISSUE TITLE
Failure to identify Raspbian Platform on Linux 5.15.84-v8+ RPiOS Lite 64bit

### ISSUE THREAD

**Issue by ztnel** [k3s-io/k3s-ansible#207]
According to my understanding RPiOS is just a rebranding of the OS previously called Raspbian. If that's the case I have recently installed a fresh image of RPiOS Lite (64-bit) and this task specifically fails to set the`detected_distribution` to Raspbian:
```yaml
    - name: Set detected_distribution to Raspbian
      set_fact:
        detected_distribution: Raspbian
      when: >
        raspberry_pi|default(false) and
        ( ansible_facts.lsb.id|default("") == "Raspbian" or
          ansible_facts.lsb.description|default("") is match("[Rr]aspbian.*") )
```

I am bringing this up since `Linux 5.15.84-v8+` does not come with cgroup support enabled and the task to enable it is in the `Raspbian.yml`:
```yaml
# tasks/prereq/Raspbian.yml
- name: Activating cgroup support
  lineinfile:
    path: /boot/cmdline.txt
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  notify: reboot
```

I'm not sure how actively this repository is maintained but I don't mind providing a patch for this if it is deemed a bug.
