### ISSUE TITLE
Stuck at TASK [k3s/node : Enable and check K3s service]

### ISSUE THREAD

**Issue by ozbillwang** [k3s-io/k3s-ansible#216]
run the playbook, stuck at task `[k3s/node : Enable and check K3s service]`

related task is 

```
- name: Enable and check K3s service
  systemd:
    name: k3s-node
    daemon_reload: yes
    state: restarted
    enabled: yes
```

If I manually ssh to node, and manually run below command

```
systemctl enable k3s-node
systemctl stop k3s-node
systemctl start k3s-node
systemctl status k3s-node
```
The service can be actived successfully. 

Then if I re-run the playbook, everything goes fine. 

So what's the problem I met?
