### ISSUE TITLE
New Install fails due to missing cgroup (v2)

### ISSUE THREAD

**Issue by DonBower** [k3s-io/k3s-ansible#219]
I have 4 brand new Raspberry Pi CM4s, running 64 bit Raspberry Pi OS Lite (no GUI), on the nodes, and with GUI on the master.
all 4 failed to start the service:
`level=fatal msg="failed to find memory cgroup (v2)"`

Your documentation should provide this as a pre-req, or add this code to your `prereq/tasks/main.yml` file:

```
- name: Enable container features
  replace:
    path: /boot/cmdline.txt
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  with_items:
  - "cgroup_enable=cpuset"
  - "cgroup_memory=1"
  - "cgroup_enable=memory"

- name: Reboot the Machine to have container features in affect
  ansible.builtin.reboot:
    reboot_timeout: 300
```

**Comment by cwayne18** [comment]
It's called out here: https://docs.k3s.io/advanced#raspberry-pi

**Comment by DonBower** [comment]
Modified:

```
- name: Enable container features
  replace:
    path: /boot/cmdline.txt
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  with_items:
  - "cgroup_memory=1"
  - "cgroup_enable=memory"
  register: boot_cmdline

- name: Reboot the Machine to have container features in affect
  ansible.builtin.reboot:
    reboot_timeout: 300
  when: boot_cmdline.changed
```
