### ISSUE TITLE
Ensure that external loadbalancer can be hit.

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s-ansible#227]
Make sure an external loadbalancer can be pointed to by the Ansible playbook. Actual deployment of the load balancer itself is not in scope.

**Comment by dereknola** [comment]
The existent of `api_endpoint` and the ability to pass `tls-san` fits completes this issue. 

```
vars:
   api_endpoint: '10.10.10.100'
   extra_server_args: "--tls-san 10.10.10.100"
   extra_agent_args: "--tls-san 10.10.10.100"
```
