### ISSUE TITLE
Errors encountered when airgap_dir is undefined

### ISSUE THREAD

**Issue by jon-stumpf** [k3s-io/k3s-ansible#257]
I attempted to create a simple cluster with three nodes.  Here is my **inventory.yml** file.
```
---
k3s_cluster:
  children:
    server:
      hosts:
        10.140.240.20:
    agent:
      hosts:
        10.140.240.21:
        10.140.240.22:

  vars:
    ansible_port: 22
    ansible_user: pi
    k3s_version: v1.26.9+k3s1
    token: "mytoken"  # Use ansible vault if you want to keep it secret
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
    extra_server_args: ""
    extra_agent_args: ""
```
When running _ansible-playbook playbook/site.yml_, I get the following errors from **role/airgap**:
```
TASK [airgap : Distribute K3s amd64 images [Airgap]] **************************************************************************************************************************************************
Tuesday 28 November 2023  12:35:25 -0500 (0:00:00.191)       0:00:44.666 ****** 
fatal: [10.140.240.20]: FAILED! => {"msg": "No file was found when using first_found. Use errors='ignore' to allow this task to be skipped if no files are found"}
fatal: [10.140.240.21]: FAILED! => {"msg": "No file was found when using first_found. Use errors='ignore' to allow this task to be skipped if no files are found"}
fatal: [10.140.240.22]: FAILED! => {"msg": "No file was found when using first_found. Use errors='ignore' to allow this task to be skipped if no files are found"}
```

This error will occur at the following locations:
- https://github.com/k3s-io/k3s-ansible/blob/1e8bfb0d3967defe66929616f50a2f40d2470a87/roles/airgap/tasks/main.yml#L60
- https://github.com/k3s-io/k3s-ansible/blob/1e8bfb0d3967defe66929616f50a2f40d2470a87/roles/airgap/tasks/main.yml#L75
- https://github.com/k3s-io/k3s-ansible/blob/1e8bfb0d3967defe66929616f50a2f40d2470a87/roles/airgap/tasks/main.yml#L90

I can add **ignore_errors: true** to the **ansible.builtin.copy** tasks to allow the playbook to proceed, but this does not seem the correct thing to do (given the error messages still produced).  And, since **airgap_dir** is not defined in my case, I don't understand why it is in the block to begin with.  See
https://github.com/k3s-io/k3s-ansible/blob/1e8bfb0d3967defe66929616f50a2f40d2470a87/roles/airgap/tasks/main.yml#L3

**Comment by dereknola** [comment]
I am unable to reproduce this issue:

Tested with 
```
---
k3s_cluster:
  children:
    server:
      hosts:
        192.168.1.91:

  # Required Vars
  vars:
    ansible_port: 22
    ansible_user: pi
    k3s_version: v1.26.9+k3s1
    token: "mytoken"  # Use ansible vault if you want to keep it secret
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
    extra_server_args: ""
    extra_agent_args: ""
```

Running `ansible-playbook -i pi.yml ./playbook/site.yml`, I see the airgap tasks being skipped as designed. (Only change is I removed the [Airgap] on all the task names).
```
TASK [prereq : Copy manifests] ***********************************************************************************************************************
skipping: [192.168.1.91]

TASK [prereq : Make config directory] ****************************************************************************************************************
skipping: [192.168.1.91]

TASK [prereq : Copy config values] *******************************************************************************************************************
skipping: [192.168.1.91]

TASK [airgap : Download k3s install script] **********************************************************************************************************
skipping: [192.168.1.91]

TASK [airgap : Distribute K3s install script] ********************************************************************************************************
skipping: [192.168.1.91]

TASK [airgap : Distribute K3s binary] ****************************************************************************************************************
skipping: [192.168.1.91]

TASK [airgap : Distribute K3s SELinux RPM] ***********************************************************************************************************
skipping: [192.168.1.91]

TASK [airgap : Install K3s SELinux RPM] **************************************************************************************************************
skipping: [192.168.1.91]

TASK [airgap : Make images directory] ****************************************************************************************************************
skipping: [192.168.1.91]

TASK [airgap : Determine Architecture] ***************************************************************************************************************
skipping: [192.168.1.91]

TASK [airgap : Distribute K3s amd64 images] **********************************************************************************************************
skipping: [192.168.1.91] => (item=/home/derek/rancher/k3s-ansible/roles/airgap/) 
skipping: [192.168.1.91]

TASK [airgap : Distribute K3s arm64 images] **********************************************************************************************************
skipping: [192.168.1.91] => (item=/home/derek/rancher/k3s-ansible/roles/airgap/) 
skipping: [192.168.1.91]

TASK [airgap : Distribute K3s arm images] ************************************************************************************************************
skipping: [192.168.1.91] => (item=/home/derek/rancher/k3s-ansible/roles/airgap/) 
skipping: [192.168.1.91]

TASK [airgap : Run K3s Install [server]] *************************************************************************************************************
skipping: [192.168.1.91]

TASK [airgap : Run K3s Install [agent]] **************************************************************************************************************
skipping: [192.168.1.91]

```
