### ISSUE TITLE
ansible script blindly overwrites existing kube config file

### ISSUE THREAD

**Issue by roivanov** [k3s-io/k3s-ansible#259]
The following piece of code does not check if file is there already.
And so may overwrite already existing config file.

```
    - name: Copy kubectl config to local machine
      ansible.builtin.fetch:
        src: ~{{ ansible_user }}/.kube/config
        dest: ~/.kube/config
        flat: true
```
