### ISSUE TITLE
config_yaml not removed when undefined

### ISSUE THREAD

**Issue by zen** [k3s-io/k3s-ansible#271]
Following the issue described in #270 , when config_yaml var is removed from inventory, resulting files are not removed.

This is caused by `when` statement in following task:

```
- name: Setup optional config file
  when: config_yaml is defined
  block:
    - name: Make config directory
      ansible.builtin.file:
        path: "/etc/rancher/k3s"
        mode: 0755
        state: directory
    - name: Copy config values
      ansible.builtin.copy:
        content: "{{ config_yaml }}"
        dest: "/etc/rancher/k3s/config.yaml"
        mode: 0644
```

Once `config_yaml` is removed from vars, the task never gets executed.
