### ISSUE TITLE
CoreDNS, local-path-provisioner, metrics-server not deployed HA in HA mode

### ISSUE THREAD

**Issue by rdvansloten** [k3s-io/k3s-ansible#305]
Hi,

I have deployed a HA Cluster using the current latest version of this role, which works fine. However, it does not spawn multiple CoreDNS and other system pods. When knocking down one node, it takes about 3-5 minutes for the system to realize that the node containing these Pods is gone and then re-deploys. Considering CoreDNS is pretty... core, this 5 minutes is a long time. I can't find any setting related to coredns or other system apps HA in this repository.

**Comment by rdvansloten** [comment]
Interim solution for CoreDNS
```
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: coredns-hpa
  namespace: kube-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: coredns
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
```

However, because CoreDNS has a topologyspread and the others don't, this can't be applied to local-path-provisioner and metrics-server.
