### ISSUE TITLE
Is these roles available through ansible-galaxy? 

### ISSUE THREAD

**Issue by vrsarin** [k3s-io/k3s-ansible#316]
Can I get ansible-galaxy namespace?

If not I would like this to be published to ansible-galaxy. What is the procedure for it?

**Comment by dereknola** [comment]
There currently isn't a plan to publish this to ansible-galaxy. The K3s organization doesn't have a good centralization around email/user accounts, so it would end up just being me as the author, which I don't really want. There is some existing boiler plate around `galaxy.yml`, so you could fork this repo and upload your own version if you wanted.

**Comment by vrsarin** [comment]
I can definitely support this. We can have a separate repo for publishing to Galaxy, but I strongly believe we should release it as the official version.

In either case, we need to coordinate on standardizing the following 
1. Release cycle
2. Versioning
3. Galaxy Account

Any thoughts?

**Comment by nonell-viavi** [comment]
I don't know if this may be helpful, but as a workaround we are currently doing this for consuming this repo through ansible galaxy:

`cat requirements.yml`

```
---
collections:
  - name: ansible.posix
    version: "1.5.4"
  - name: k3s/orchestration
    source: https://github.com/k3s-io/k3s-ansible.git
    version: 7ec16a8d53363ace979e5585323311ab1bd1641d # 2024/04/05
    type: git
```

Then
`ansible-galaxy collection install -r requirements.yml` installs this repo under `<COLLECTIONS_PATH>/ansible-collections/k3s-orchestration`.

And you can use it like:
`ansible-playbook -i inventory.ini ansible_collections/k3s/orchestration/playbook/site.yml`
