### ISSUE TITLE
ansible lint, playbooks folder, and firewalld

### ISSUE THREAD

**Issue by psztoch** [k3s-io/k3s-ansible#321]
1. playbook folder should be renamed to playbooks - `ansible-playbook k3s.orchestration.site` will not works without it .
2. ansible-lint - please fix warings or add ignore comment `# noqa: ...`
3. Zone trusted accept traffic to all ports. What is the purpose of these tasks?
```
    - name: If firewalld enabled, open api port
      ansible.posix.firewalld:
        port: "{{ api_port }}/tcp"
        zone: trusted
        state: enabled
        permanent: true
        immediate: true

    - name: If firewalld enabled, open etcd ports
      when: groups['server'] | length > 1
      ansible.posix.firewalld:
        port: "2379-2381/tcp"
        zone: trusted
        state: enabled
        permanent: true
        immediate: true
```
It will be ok for 'zone: internal'. Then public IPs of cluster nodes can be added to 'internal' zones.
4. token and other parameters should be 'k3s_' prefixed
