### ISSUE TITLE
Playbook fails when used with AWS hosts with SSH over SSM connection

### ISSUE THREAD

**Issue by strophy** [k3s-io/k3s-ansible#349]
The readme for this repo states that "All managed nodes in inventory must have passwordless SSH access". I'm curious about why this is, and if it is possible to use the playbook with hosts using SSH tunneled over an AWS SSM connection. My inventory looks like this:
```
---
plugin: amazon.aws.aws_ec2
region: eu-west-1
keyed_groups:
  - prefix: service
    key: tags.service
  - prefix: subservice
    key: tags.subservice
hostnames:
  - instance-id
filters:
  vpc-id: vpc-02b3f4d50b1ffeb5c
  "tag:env": "prod"
compose:
  instance_hostname: tags.hostname
  is_rancher_service: true if 'rancher' in tags.service else false # Needed for k3s.orchestration collection
groups:
  server: is_rancher_service
  k3s_cluster: is_rancher_service
```

My playbook looks like this:
```
---

- name: Prepare hosts
  hosts: service_rancher
  become: true
  roles:
    - role: ubuntu_host
      ubuntu_host_skip_docker_install: true
    - role: cw_agent

- name: Run the k3s/orchestration site.yml playbook
  ansible.builtin.import_playbook: k3s.orchestration.site # noqa yaml[schema]
```

The first two roles run fine over the SSM connection. When we get to the imported playbook, I get this error:
```
PLAYBOOK: setup-rancher.yml ***********************************************************************************************************************************************************************************************************************************************************************************************************
Positional arguments: setup-rancher.yml
verbosity: 5
connection: ssh
become_method: sudo
tags: ('all',)
inventory: ('/home/leon/Code/infra/ansible/inventories/prod',)
forks: 5
3 plays in setup-rancher.yml

PLAY [Cluster prep] *******************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /home/leon/.ansible/collections/ansible_collections/k3s/orchestration/playbooks/site.yml:2
Loading collection community.aws from /home/leon/.ansible/collections/ansible_collections/community/aws
<i-0606aca98ce3f2750> ESTABLISH SSM CONNECTION TO: i-0606aca98ce3f2750
<i-0606aca98ce3f2750> INITIALIZE BOTO3 CLIENTS
<i-0606aca98ce3f2750> SETUP BOTO3 CLIENTS: SSM
<i-0606aca98ce3f2750> _get_bucket_endpoint: S3 (global)
<i-0606aca98ce3f2750> ssm_retry: attempt: 0, caught exception(expected string or bytes-like object, got 'NoneType') from cmd (echo ~...), pausing for 0 seconds
<i-0606aca98ce3f2750> ESTABLISH SSM CONNECTION TO: i-0606aca98ce3f2750
<i-0606aca98ce3f2750> INITIALIZE BOTO3 CLIENTS
<i-0606aca98ce3f2750> SETUP BOTO3 CLIENTS: SSM
<i-0606aca98ce3f2750> _get_bucket_endpoint: S3 (global)
<i-0606aca98ce3f2750> ssm_retry: attempt: 1, caught exception(expected string or bytes-like object, got 'NoneType') from cmd (echo ~...), pausing for 1 seconds
<i-0606aca98ce3f2750> ESTABLISH SSM CONNECTION TO: i-0606aca98ce3f2750
<i-0606aca98ce3f2750> INITIALIZE BOTO3 CLIENTS
<i-0606aca98ce3f2750> SETUP BOTO3 CLIENTS: SSM
<i-0606aca98ce3f2750> _get_bucket_endpoint: S3 (global)
<i-0606aca98ce3f2750> ssm_retry: attempt: 2, caught exception(expected string or bytes-like object, got 'NoneType') from cmd (echo ~...), pausing for 3 seconds
<i-0606aca98ce3f2750> ESTABLISH SSM CONNECTION TO: i-0606aca98ce3f2750
<i-0606aca98ce3f2750> INITIALIZE BOTO3 CLIENTS
<i-0606aca98ce3f2750> SETUP BOTO3 CLIENTS: SSM
<i-0606aca98ce3f2750> _get_bucket_endpoint: S3 (global)
```
The same "Gathering Facts" step works for the previous roles I included:
```
PLAYBOOK: setup-rancher.yml ***********************************************************************************************************************************************************************************************************************************************************************************************************
Positional arguments: setup-rancher.yml
verbosity: 5
connection: ssh
become_method: sudo
tags: ('all',)
inventory: ('/home/leon/Code/infra/ansible/inventories/prod',)
forks: 5
4 plays in setup-rancher.yml

PLAY [Prepare hosts] ******************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /home/leon/Code/infra/ansible/setup-rancher.yml:3
Loading collection community.aws from /home/leon/.ansible/collections/ansible_collections/community/aws
<i-0606aca98ce3f2750> ESTABLISH SSM CONNECTION TO: i-0606aca98ce3f2750
<i-0606aca98ce3f2750> INITIALIZE BOTO3 CLIENTS
<i-0606aca98ce3f2750> SETUP BOTO3 CLIENTS: SSM
<i-0606aca98ce3f2750> _get_bucket_endpoint: S3 (global)
<i-0606aca98ce3f2750> _get_bucket_endpoint: S3 (bucket region) - eu-west-1
<i-0606aca98ce3f2750> SETUP BOTO3 CLIENTS: S3 https://s3.eu-west-1.amazonaws.com
<i-0606aca98ce3f2750> START SSM SESSION: i-0606aca98ce3f2750
<i-0606aca98ce3f2750> SSM COMMAND: ['/usr/local/bin/session-manager-plugin', '{"SessionId": "leonwhite-373hs3yhptu4manylzdo25ac74", "TokenValue": "<snipped>", "StreamUrl": "wss://ssmmessages.eu-west-1.amazonaws.com/v1/data-channel/leonwhite-373hs3yhptu4manylzdo25ac74?role=publish_subscribe&cell-number=<snipped>", "ResponseMetadata": {"RequestId": "d820b582-4657-422a-8d37-e6b7efe7fa81", "HTTPStatusCode": 200, "HTTPHeaders": {"server": "Server", "date": "Tue, 23 Jul 2024 09:36:05 GMT", "content-type": "application/x-amz-json-1.1", "content-length": "1117", "connection": "keep-alive", "x-amzn-requestid": "d820b582-4657-422a-8d37-e6b7efe7fa81"}, "RetryAttempts": 0}}', 'eu-west-1', 'StartSession', '', '{"Target": "i-0606aca98ce3f2750"}', 'https://ssm.eu-west-1.amazonaws.com']
<i-0606aca98ce3f2750> PRE stdout line: 
b'\r\nStarting session with SessionId: leonwhite-373hs3yhptu4manylzdo25ac74\r\n'
<i-0606aca98ce3f2750> PRE startup output received
<i-0606aca98ce3f2750> PRE Disabling Echo: b'stty -echo\n'
<i-0606aca98ce3f2750> PRE remaining: 60
<i-0606aca98ce3f2750> PRE stdout line: 
.....
```
What could be going wrong here?
