### ISSUE TITLE
API server not running after install

### ISSUE THREAD

**Issue by rdong8** [k3s-io/k3s-ansible#359]
I'm trying to provision a single-node K8s cluster in Oracle Cloud. The instance is running Fedora Server 40. However, after the install finishes, I do not see the API server running, and `kubectl` only works from the server node itself.

`kubectl get all --all-namespaces`

```
NAMESPACE     NAME                                          READY   STATUS      RESTARTS   AGE
kube-system   pod/coredns-576bfc4dc7-9m4pt                  1/1     Running     0          3m43s
kube-system   pod/helm-install-traefik-crd-hhxwk            0/1     Completed   0          3m44s
kube-system   pod/helm-install-traefik-wbtgp                0/1     Completed   1          3m44s
kube-system   pod/local-path-provisioner-86f46b7bf7-h4sjk   1/1     Running     0          3m43s
kube-system   pod/metrics-server-557ff575fb-jth5t           1/1     Running     0          3m43s
kube-system   pod/svclb-traefik-0c766709-ptn7p              2/2     Running     0          3m34s
kube-system   pod/traefik-5fb479b77-5tg7p                   1/1     Running     0          3m34s

NAMESPACE     NAME                     TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
default       service/kubernetes       ClusterIP      10.43.0.1       <none>        443/TCP                      3m59s
kube-system   service/kube-dns         ClusterIP      10.43.0.10      <none>        53/UDP,53/TCP,9153/TCP       3m55s
kube-system   service/metrics-server   ClusterIP      10.43.222.87    <none>        443/TCP                      3m54s
kube-system   service/traefik          LoadBalancer   10.43.177.211   10.0.0.125    80:30582/TCP,443:31957/TCP   3m34s

NAMESPACE     NAME                                    DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   daemonset.apps/svclb-traefik-0c766709   1         1         1       1            1           <none>          3m34s

NAMESPACE     NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns                  1/1     1            1           3m55s
kube-system   deployment.apps/local-path-provisioner   1/1     1            1           3m55s
kube-system   deployment.apps/metrics-server           1/1     1            1           3m55s
kube-system   deployment.apps/traefik                  1/1     1            1           3m34s

NAMESPACE     NAME                                                DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/coredns-576bfc4dc7                  1         1         1       3m44s
kube-system   replicaset.apps/local-path-provisioner-86f46b7bf7   1         1         1       3m44s
kube-system   replicaset.apps/metrics-server-557ff575fb           1         1         1       3m44s
kube-system   replicaset.apps/traefik-5fb479b77                   1         1         1       3m34s

NAMESPACE     NAME                                 STATUS     COMPLETIONS   DURATION   AGE
kube-system   job.batch/helm-install-traefik       Complete   1/1           12s        3m53s
kube-system   job.batch/helm-install-traefik-crd   Complete   1/1           11s        3m53s
```

I've attached the output from the Ansible script and the `journalctl -u k3s -b 0` output as well. 

[outputs.zip](https://github.com/user-attachments/files/16939796/outputs.zip)

My inventory file:

```yml
k3s_cluster:
  children:
    server:
      hosts:
        MY-SERVER-IP:
    agent:
      hosts:

  # Required Vars
  vars:
    ansible_port: 22
    ansible_user: "rdong"
    k3s_version: "v1.30.2+k3s1"
    # The token should be a random string of reasonable length. You can generate
    # one with the following commands:
    # - openssl rand -base64 64
    # - pwgen -s 64 1
    # You can use ansible-vault to encrypt this value / keep it secret.
    token: ""
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
    extra_server_args: ""
    extra_agent_args: ""

    # Optional vars

    # cluster_context: k3s-ansible
    # api_port: 6443
    # k3s_server_location: /var/lib/rancher/k3s
    # systemd_dir: /etc/systemd/system
    # extra_service_envs: [ 'ENV_VAR1=VALUE1', 'ENV_VAR2=VALUE2' ]
    # user_kubectl: true, by default kubectl is symlinked and configured for use by ansible_user. Set to false to only kubectl via root user.

    # Manifests or Airgap should be either full paths or relative to the playbook directory.
    # List of locally available manifests to apply to the cluster, useful for PVCs or Traefik modifications.
    # extra_manifests: [ '/path/to/manifest1.yaml', '/path/to/manifest2.yaml' ]
    # airgap_dir: /tmp/k3s-airgap-images

    server_config_yaml:  |
      # This is now an inner yaml file. Maintain the indentation.
      # YAML here will be placed as the content of /etc/rancher/k3s/config.yaml
      # See https://docs.k3s.io/installation/configuration#configuration-file
      write-kubeconfig-mode: "0644"
    # registries_config_yaml:  |
    #   Containerd can be configured to connect to private registries and use them to pull images as needed by the kubelet.
    #   YAML here will be placed as the content of /etc/rancher/k3s/registries.yaml
    #   See https://docs.k3s.io/installation/private-registry
```

I've tried reinstalling a few times but I never see the API server running.
