### ISSUE TITLE
Airgap install throws token must not be empty 

### ISSUE THREAD

**Issue by GitHanter** [k3s-io/k3s-ansible#361]
Airgap install throws token must not be empty

Seems the latest security fix by "using K3S_TOKEN environment variable " commit caused this issue [Security exposure related to the token (https://github.com/k3s-io/k3s-ansible/pull/356)](https://github.com/k3s-io/k3s-ansible/commit/2d98982809f878b9e02567236e42b2a350542082)

**Comment by dereknola** [comment]
You always have to provide a token in the inventory.yaml, PR #356 didn't change that requirement. What exactly is the error you are seeing.

**Comment by GitHanter** [comment]
> You always have to provide a token in the inventory.yaml, PR #356 didn't change that requirement. What exactly is the error you are seeing.

I provided the token the inventory.yaml, but it's not working. I have to append the `--token` parameter to the systemd service again `ExecStart=/usr/local/bin/k3s server --cluster-init --data-dir {{ k3s_server_location }} --token {{ token }} {{ extra_server_args }} `, which is deleted in the PR, then everything works.

**Comment by dereknola** [comment]
I tested this out, and I'm still not seeing the issue as you described. My setup was a airgapped cluster of pi4s with my inventory.yml looking like:
```
---
k3s_cluster:
  children:
    server:
      hosts:
        # localhost:
        192.168.1.91:
    agent:
      hosts:
         192.168.1.92:
  # Required Vars
  vars:
    #ansible_port: 22
    ansible_user: "pi"
    airgap_dir: "./my-airgap"
    # k3s_version: v1.28.11+k3s1
    token: "mytoken"  # Use ansible vault if you want to keep it secret
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
    extra_server_args: ""
    extra_agent_args: ""
```
What does your inventory look like?

**Comment by GitHanter** [comment]
This is my inventory, I try to setup the kubernetes cluster in my raspberry pi cm4 cluster

```yml
k3s_cluster:
  children:
    server:
      hosts:
        rpicm404:
    agent:
      hosts:
        rpicm401:
        rpicm402:
        rpicm403:


  # Required Vars
  vars:
    ansible_port: 22
    k3s_version: v1.31.0+k3s1
    token: "<The-token>"
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
    extra_server_args: "--flannel-backend=none --disable-network-policy --disable-helm-controller --disable-cloud-controller --disable=servicelb --disable=traefik"
    extra_agent_args: ""
    airgap_dir: /<the-base-dir>/k3s-airgap/v1.31.0+k3s1
```
