### ISSUE TITLE
Some file are not created (k3s.service.env, k3s-agent.service.env)

### ISSUE THREAD

**Issue by jkrenzer** [k3s-io/k3s-ansible#368]
Hi!

Due to the missing parameter `create: true` in the `ansible.builtin.lineinfile` command, some files are not created when they are empty and thus an installation from a clean system fails.

So far I identified following steps:

In roles/k3s_server/tasks/main.yaml:
- Add service environment variables
- Add token as an environment variable

In roles/k3s_agent/tasks/main.yaml:
- Add the token for joining the cluster to the environment

Cheers,

Jörn

**Comment by dereknola** [comment]
K3s-ansible is not responsible for creating the `k3s.service.env` file. That is created by the k3s install script. https://github.com/k3s-io/k3s/blob/master/install.sh#L961. What types of errors are you seeing?

**Comment by jkrenzer** [comment]
First the errors were censored, when setting `no_log: false` in the aforementioned tasks it was a file not found error. 

System is a freshly installed Debian 11/bullseye server, ansible collection is from the master branch here.

**Comment by sky003** [comment]
I probably have a similar issue. Perhaps it has something to do with this change https://github.com/k3s-io/k3s-ansible/commit/bc03d1c0d053bb3e3362c526aa38bc8762d1f816

This file is not created `{{ systemd_dir }}/k3s-agent.service.env`. And I don't see where it's supposed to be created by k3s. 

So probably we should test the file before running the task:
```
- name: Add the token for joining the cluster to the environment
  no_log: false # avoid logging the server token
  ansible.builtin.lineinfile:
    path: "{{ systemd_dir }}/k3s-agent.service.env"
    line: "{{ item }}"
  with_items:
    - "K3S_TOKEN={{ token }}"
  when: "'{{ systemd_dir }}/k3s-agent.service.env' is file"
```
