### ISSUE TITLE
No K3S binary found AirGap installation.

### ISSUE THREAD

**Issue by yasvanth** [k3s-io/k3s-ansible#386]
Hi Team,

I am setting up k3s cluster using `k3s-anisble` via AirGap Installation where the nodes doesn't have access to internet to download `k3s` binary. 

<pre>
TASK [airgap : Run K3s Install [server]] *******************************************************************************************************
 {"changed": true, "cmd": ["/usr/local/bin/k3s-install.sh"], "delta": "0:00:00.008579", "end": "2025-01-07 09:52:10.474909", "msg": "non-zero return code", "rc": 1, "start": "2025-01-07 09:52:10.466330", "stderr": "[ERROR]  Executable k3s binary not found at /usr/local/bin/k3s", "stderr_lines": ["[ERROR]  Executable k3s binary not found at /usr/local/bin/k3s"], "stdout": "[INFO]  Skipping k3s download and verify", "stdout_lines": ["[INFO]  Skipping k3s download and verify"]}

TASK [airgap : Run K3s Install [agent]] ********************************************************************************************************
fatal: []: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/k3s-install.sh"], "delta": "0:00:00.009723", "end": "2025-01-07 09:52:10.884947", "msg": "non-zero return code", "rc": 1, "start": "2025-01-07 09:52:10.875224", "stderr": "[ERROR]  Executable k3s binary not found at /usr/local/bin/k3s", "stderr_lines": ["[ERROR]  Executable k3s binary not found at /usr/local/bin/k3s"], "stdout": "[INFO]  Skipping k3s download and verify", "stdout_lines": ["[INFO]  Skipping k3s download and verify"]}
fatal: []: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/k3s-install.sh"], "delta": "0:00:00.007053", "end": "2025-01-07 09:52:10.933546", "msg": "non-zero return code", "rc": 1, "start": "2025-01-07 09:52:10.926493", "stderr": "[ERROR]  Executable k3s binary not found at /usr/local/bin/k3s", "stderr_lines": ["[ERROR]  Executable k3s binary not found at /usr/local/bin/k3s"], "stdout": "[INFO]  Skipping k3s download and verify", "stdout_lines": ["[INFO]  Skipping k3s download and verify"]}
fatal: []: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/k3s-install.sh"], "delta": "0:00:00.009759", "end": "2025-01-07 09:52:10.996794", "msg": "non-zero return code", "rc": 1, "start": "2025-01-07 09:52:10.987035", "stderr": "[ERROR]  Executable k3s binary not found at /usr/local/bin/k3s", "stderr_lines": ["[ERROR]  Executable k3s binary not found at /usr/local/bin/k3s"], "stdout": "[INFO]  Skipping k3s download and verify", "stdout_lines": ["[INFO]  Skipping k3s download and verify"]}

</pre>

Inspecting `roles/airgap/tasks/mail.yaml`, I found that there is no task to download `k3s` binary on the control machine (localhost) after adding below task resolves the issue. Is there any reason why `k3s` binary is download task is not available?

```yaml 
    - name: Check for k3s binary
      become: false
      delegate_to: localhost
      ansible.builtin.stat:
        path: "{{ airgap_dir + '/k3s' }}"
      register: k3s_binary

    - name: Download k3s binary
      become: false
      delegate_to: localhost
      # Workaround for https://github.com/ansible/ansible/issues/64016
      when: not k3s_binary.stat.exists
      ansible.builtin.get_url:
        url: "https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s"
        timeout: 120
        dest: "{{ airgap_dir }}/k3s"
        mode: "0755"
```
