### ISSUE TITLE
k3s-agent.service.env does not exist

### ISSUE THREAD

**Issue by mvallebr** [k3s-io/k3s-ansible#415]
Hi, I imported the roles available in this repo using ansible galaxy and I tried to run on a [multipass](https://canonical.com/multipass) environment (ubuntu 24.04). 

I was getting an error hard to debug, in the task "Add the token for joining the cluster to the environment". Hard to debug, because no logs were being generated.

I have then copied all tasks to my local role and I could see the error:

```
TASK [k3s_cluster : Add the token for joining the cluster to the environment] **********************************
failed: [k3s-test] (item=K3S_TOKEN=*HIDDEN*) => {"ansible_loop_var": "item", "changed": false, "item": "K3S_TOKEN=*HIDDEN*", "msg": "Destination /etc/systemd/system/k3s-agent.service.env does not exist !", "rc": 257}
```

I checked and the folder `/etc/systemd/system/` does exist in the server, but it seems this task was expecting this file to be there, but it is not being created anywhere, not even on server or prereq roles, which I executed successfully before this one. 

I could be wrong, but it seems the agent role is broken then? Should a task to create this file be added?

Something like below, maybe?

```
- name: Ensure k3s-agent.service.env exists
  ansible.builtin.file:
    path: "{{ systemd_dir }}/k3s-agent.service.env"
    state: touch
    owner: root
    group: root
    mode: "0644"  
```
