### ISSUE TITLE
Airgap distribute k3s binary runs even without airgap enabled

### ISSUE THREAD

**Issue by gustavlasko** [k3s-io/k3s-ansible#417]
When installing from ansible-galaxy, I get error:
```
TASK [k3s.orchestration.airgap : Distribute K3s binary {{ k3s_arch }}] **********************************************************************************************************
fatal: [192.168.50.100]: FAILED! => {"msg": "No file was found when using first_found."}
```

Steps to reproduce:
- inventory.yaml:
```
---

k3s_cluster:
  children:
    server:
      hosts:
        192.168.50.100:
    agent:
      hosts:
        192.168.50.100:
  vars:
    k3s_version: v1.30.2+k3s1
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
```

Get the latest playbooks:
`ansible-galaxy collection install git+https://github.com/k3s-io/k3s-ansible.git`
Install new cluster:
`ansible-playbook k3s.orchestration.site -i inventory.yml`
