### ISSUE TITLE
Update k3s_version to v1.19.2+k3s1 (or whatever's latest)

### ISSUE THREAD

**Issue by geerlingguy** [k3s-io/k3s-ansible#94]
It would be nice to get off 1.17 (which is the current version this playbook installs), but there is one caveat—at least in some testing from @alexellis—it seems that K3s 1.19 may have issues running on older Pis like the Pi 3 B+ due to network timeouts or disk IO speed (see https://github.com/rancher/k3s/issues/2353).

**Comment by mfonner** [comment]
For those of us that want to test the newer version, that should be as simple as changing 

`k3s_version: v1.17.5+k3s1`

In inventory/sample/group_vars/all.yml correct? I don't see any version specific configurations, to my knowledge so far, in any of the roles.

**Comment by nicklasfrahm** [comment]
I don't know if this is something that would be interesting for this project, but I made it automatically update my cluster to the latest stable via these ansible tasks:

```yaml
- name: Get latest k3s version
  uri:
    url: https://update.k3s.io/v1-release/channels/latest
    follow_redirects: 'yes'
  register: response

- name: Download k3s binary version {{ response.url.split('/')[-1] }} (x86_64)
  become: yes
  when: ansible_facts['architecture'] == "x86_64"
  get_url:
    url: "https://github.com/rancher/k3s/releases/download/{{ response.url.split('/')[-1] }}/k3s"
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: '0755'
    force: yes
```

Maybe we could make the channel a variable? 🤔
