### ISSUE TITLE
SEC: Support SELinux

### ISSUE THREAD

**Issue by westurner** [k3s-io/k3s-ansible#98]
It'd be great to have optional support for SELinux: https://rancher.com/docs/k3s/latest/en/advanced/#experimental-selinux-support

From  https://github.com/rancher/k3s/issues/2473#issuecomment-723346270 :

k3s-ansible (an excellent reference for the necessary setup steps) could be updated here as well: https://github.com/rancher/k3s-ansible/blob/721c3487027e42d30c60eb206e0fb5abfddd094f/roles/prereq/tasks/main.yml#L2-L5

OTOH something like this:

```yaml
- name: Set SELinux to disabled state
  selinux:
    state: disabled
  when:
    - not (k3s_disable_selinux is defined and not k3s_disable_selinux) or k3s_disable_selinux == False
    - ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']
```

With this added to https://github.com/rancher/k3s-ansible/blob/master/inventory/sample/group_vars/all.yml :

```yaml
k3s_disable_selinux: False
```
